name: the_bridge_app
description: "An app to share the gospel using the bridge illustration"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.9.1
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  provider: ^6.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_colorpicker: ^1.0.3
  fluttertoast: ^8.2.8
  sqflite: ^2.0.1
  path: ^1.8.0
  intl: ^0.19.0
  scribble: ^0.10.0+1
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.2.5
  audioplayers: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  html_unescape: ^2.0.0
  characters: ^1.3.0
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/bridge_diagram.png
    - assets/home.png
    - assets/video/output_video_1.mp4
    - assets/video/output_video_2.mp4
    - assets/video/output_video_3.mp4
    - assets/video/output_video_4.mp4
    - assets/video/output_video_5.mp4
    - assets/video/output_video_6.mp4
    - assets/video/output_video_7.mp4
    - assets/video/output_video_8.mp4
    - assets/video/output_video_9.mp4
    - assets/video/output_video_10.mp4
    - assets/video/output_video_11.mp4
    - assets/video/output_video_12.mp4
    - assets/video/output_video_13.mp4
    - assets/video/output_video_14.mp4
    - assets/video/output_video_15.mp4
    - assets/video/output_video_16.mp4
    - assets/video/output_video_17.mp4
    - assets/video/output_video_18.mp4
    - assets/video/output_video_19.mp4
    - assets/audio/audio_step_1.mp3
    - assets/audio/audio_step_2.mp3
    - assets/audio/audio_step_3.mp3
    - assets/audio/audio_step_4.mp3
    - assets/audio/audio_step_5.mp3
    - assets/audio/audio_step_6.mp3
    - assets/audio/audio_step_7.mp3
    - assets/audio/audio_step_8.mp3
    - assets/audio/audio_step_9.mp3
    - assets/audio/audio_step_10.mp3
    - assets/audio/audio_step_11.mp3
    - assets/audio/audio_step_12.mp3
    - assets/audio/audio_step_13.mp3
    - assets/audio/audio_step_14.mp3
    - assets/audio/audio_step_15.mp3
    - assets/audio/audio_step_16.mp3
    - assets/audio/audio_step_17.mp3
    - assets/audio/audio_step_18.mp3
    - assets/audio/audio_step_19.mp3
    - assets/illustrations/welcome.svg
    - assets/illustrations/onboarding_welcome.svg
    - assets/illustrations/personality.svg
    - assets/illustrations/conversation.svg
    - assets/illustrations/question_bank.svg
    - assets/illustrations/no_notes.svg
    - assets/illustrations/no_matches.svg
    - assets/illustrations/onboarding_conversation.svg
    - assets/illustrations/notes.svg
    - assets/illustrations/resources.svg
    - assets/illustrations/loading_notes.svg
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
