// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZN3TUqJCGg9eVUWEZvemlg1SWt0xQ1ho',
    appId: '1:572750242114:android:e7df5a1fbd8aee9311e8db',
    messagingSenderId: '572750242114',
    projectId: 'thebridge-admin',
    storageBucket: 'thebridge-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKIxoRg3XrOl4IySbfgqPzItC0UIvork',
    appId: '1:572750242114:ios:b0c07e00798b0f4211e8db',
    messagingSenderId: '572750242114',
    projectId: 'thebridge-admin',
    storageBucket: 'thebridge-admin.firebasestorage.app',
    iosBundleId: 'com.example.thebridgeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKIxoRg3XrOl4IySbfgqPzItC0UIvork',
    appId: '1:572750242114:ios:78bce0de3b0ce4b811e8db',
    messagingSenderId: '572750242114',
    projectId: 'thebridge-admin',
    storageBucket: 'thebridge-admin.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSCKYh9lnyXOaZQrPITO9NvyMzQgWK2QE',
    appId: '1:572750242114:web:e69f2a2cfe8181a311e8db',
    messagingSenderId: '572750242114',
    projectId: 'thebridge-admin',
    authDomain: 'thebridge-admin.firebaseapp.com',
    storageBucket: 'thebridge-admin.firebasestorage.app',
  );
}
